version: "3.9"

services:
  web:
    image: bisheklpu/heart-disease-classifier:${IMAGE_TAG:-1.0.1}
    container_name: heart-disease-classifier

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "80:80"
    environment:
      - PORT=80

    env_file:
      - .env 
    
    restart: unless-stopped