version: "3.9"

services:
  web:
    image: bisheklpu/heart-disease-classifier:latest
    container_name: heart-disease-classifier
    restart: always

    # build:
    #   context: .
    #   dockerfile: Dockerfile

    # environment:
    #   PORT: ${PORT}
    #   OPENAI_API_KEY: ${OPENAI_API_KEY}


    env_file:
      - .env 


    labels:
      - "traefik.enable=true"
      # domain
      - "traefik.http.routers.heart.rule=Host(`heart.bishek.in`)"
      # https entrypoint
      - "traefik.http.routers.heart.entrypoints=websecure"
      # ssl
      - "traefik.http.routers.heart.tls.certresolver=letsencrypt"
      # container port
      - "traefik.http.services.heart.loadbalancer.server.port=80"

volumes:
  traefik-letsencrypt: